apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: app-backend-container
        image: docai-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: apikey-secret
